package Common;

/**
 * 
 * @author renato
 * @author ruben
 */
public enum MessageType {

	// pilot
	INFORMPLANEREADYFORBOARDING,
	WAITFORALLINBOARD,
	FLYTODESTINATIONPOINT,
	ANNOUNCEARRIVAL,
	FLYTODEPARTUREPOINT,
	PARKATTRANSFERGATE,
	PILOTFINISHACTIVITY,

	// hostess
	PREPAREFORPASSBOARDING,
	CHECKDOCUMENTS,
	WAITFORNEXTPASSENGER,
	INFORMPLANEREADYTOTAKEOFF,
	WAITFORNEXTFLIGHT,
	
	// passanger
	TRAVELTOAIRPORT,
	WAITINQUEUE,
	SHOWDOCUMENTS,
	BOARDTHEPLANE,
	WAITFORENDOFFLIGHT,
	LEAVETHEPLANE,
	
	// states
	SETPILOTSTATE,
	SETPASSENGERSTATE,
	SETHOSTESSSTATE,
	
	// stop shared region
	ISSTOPPED,
	
	// number voo
	NUMBERVOO,
}
